version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./ecommerce.db
      - SECRET_KEY=your_secret_key
    volumes:
      - ./backend:/app
